-   id: js-beautify
    name: js-beautify
    entry: js-beautify
    language: node
    'types': [text]
    args: []
    require_serial: false
    additional_dependencies: ["js-beautify@1.8.10-beta1"]
